### Tensor Initialization

In [2]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [7]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor : \n {x_rand} \n")

Random Tensor : 
 tensor([[0.0027, 0.5221],
        [0.4386, 0.0423]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor}\n")
print(f"Ones Tensor : \n {ones_tensor}\n")
print(f"Zeros Tensor : \n {zeros_tensor}\n")


Random Tensor : 
 tensor([[0.6041, 0.1963, 0.8517],
        [0.6455, 0.7621, 0.7215]])

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



### Tensor Attributes

In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : \n {tensor.shape}\n")
print(f"Datatype of tensor :\n {tensor.dtype}\n")
print(f"Device tensor is stored on : \n {tensor.device}\n")


Shape of tensor : 
 torch.Size([3, 4])

Datatype of tensor :
 torch.float32

Device tensor is stored on : 
 cpu



### Tensor Operations

In [15]:
# move out tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
tensor

tensor([[0.4512, 0.5541, 0.4853, 0.4000],
        [0.0334, 0.1850, 0.6018, 0.5590],
        [0.9765, 0.4452, 0.7517, 0.5004]], device='cuda:0')

In [16]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [18]:
## torch.cat / torch.stack : concatenate tensors with given axis
t1 = torch.cat([tensor,tensor,tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [20]:
## This computes the element-wise product : 2 ways
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

print(f"tensor * tensor \n {tensor*tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
## Matrix multiplications
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}")

print(f"tensor @ tensor.T\n {tensor@tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor @ tensor.T
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [23]:
## In-place computation : use function with _
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


### Share memory with Numpy arrays when used in CPU

In [27]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [29]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [30]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [32]:
## Numpy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [33]:
np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
