### Tensor Initialization

In [2]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [7]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Random Tensor : \n {x_rand} \n")

Random Tensor : 
 tensor([[0.0027, 0.5221],
        [0.4386, 0.0423]]) 



In [10]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor : \n {rand_tensor}\n")
print(f"Ones Tensor : \n {ones_tensor}\n")
print(f"Zeros Tensor : \n {zeros_tensor}\n")


Random Tensor : 
 tensor([[0.6041, 0.1963, 0.8517],
        [0.6455, 0.7621, 0.7215]])

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



### Tensor Attributes

In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor : \n{tensor.shape}\n")
print(f"Datatype of tensor :\n{tensor.dtype}\n")
print(f"Device tensor is stored on : \n{tensor.device}\n")


Shape of tensor : 
torch.Size([3, 4])

Datatype of tensor :
 torch.float32

Device tensor is stored on : 
cpu

